### ISSUE TITLE
关于行距和打开窗口大小问题

### ISSUE THREAD

**Issue by bashang03** [Beyondcow/BeyondcowTxtReader#15]
新版本最宽行距只能调整到3，不能自己输入数字调整。
个人比较喜欢宽行距的阅读感，希望能够增加用户调整的空间

另外每次打开的软件，窗口大小都是固定大小，希望能够默认为上一次最后关闭窗口的大小

**Comment by keefo** [comment]
谢谢反馈，新版本将解决这些问题。

**Comment by keefo** [comment]
行距问题已经在 1.8 版本解决。应该可以更新了。
窗口大小问题，我们会在后续版本处理。
