### ISSUE TITLE
[Feature Request] 英文界面

### ISSUE THREAD

**Issue by hoyang** [Beyondcow/BeyondcowTxtReader#16]
在 AppStore 买个一份，安装后的应用名称是：超牛txt小说阅读器，

系统是英文的，绝大部分App都是英文的，这个App是中文的，请问能不能加个英文版本，跟随系统的设置呢？

App的每方面都超赞，堪称 pixel-perfect，唯这点能有的话就很棒（要是应用的界面也能有英文版本，简直会让强迫症患者激动的说不出话来）。

**Comment by keefo** [comment]
收到。我们会排期开发。

**Comment by hoyang** [comment]
太棒了！1.9 有了英文界面。
