### ISSUE TITLE
mac版本点击关闭和目录软件崩溃

### ISSUE THREAD

**Issue by comingsun** [Beyondcow/BeyondcowTxtReader#17]
4月11日升级新版本后出现打开txt文件后点击文件目录图标软件崩溃，无响应只能强制退出。同时点击窗口左上方关闭图标同样会出现程序无响应只能强制退出。（mac最新版本）

**Comment by BeyondcowSupport** [comment]
谢谢反馈。请问这个情况是每本书都有？还是特定的一本书出现的？

**Comment by comingsun** [comment]
应该是特定某本书的问题

**Comment by keefo** [comment]
谢谢反馈，已经找到问题。
1.8.3 版本已经提审。

**Comment by keefo** [comment]
1.8.3 已经发布。请更新后试着打开，如果问题解决了。请这里留言谢谢。

**Comment by comingsun** [comment]
已解决
