### ISSUE TITLE
元信息搜索无结果

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#18]
尝试手动搜索了起点排行前五的几个书名均无结果
有一条相关日志
```
 11 2019-04-15 10:40:37.863 -       ERROR - <<2   超牛txt小说阅读器            0x000000010ccd2154 超牛txt小说阅读器 + 520532>> - addFetchJob error: (null)
```

另外，手动搜索中回车键无法提交搜索

**Comment by keefo** [comment]
API 会记录匹配失败的请求，然后我们会补充书籍信息。所以稍后也许就可以搜到了。
当然，我们不记录请求者是谁，所以你需要自己重新搜索才能看到变化。

**Comment by keefo** [comment]
现在搜索试试看。

**Comment by keefo** [comment]
如果还是搜不到，请把书名和作者发来。

**Comment by Csineneo** [comment]
依然搜不到
书名： 全球高武
作者： 老鹰吃小鸡

![image](https://user-images.githubusercontent.com/1370009/56123576-50b92980-5fa7-11e9-9372-0e5dc4715d12.png)

**Comment by keefo** [comment]
API 设计的是如果提交的书籍信息和书名作者不匹配是无法搜到结果的。例如：这里你手动输入的书名，作者还会和文字的前几段一起提交匹配。可能是因为书名和文章内容不匹配导致没搜到。

因为文章前几段往往包含：作者：xxx 这样的信息，API 会把这类关键词也考虑进去。

如果你的书是这本，肯定可以搜到的。我刚试验过。
<img width="645" alt="Screen Shot 2019-04-15 at 8 51 01 AM" src="https://user-images.githubusercontent.com/809588/56146756-a7991180-5f5b-11e9-847e-856cb2adaf50.png">

**Comment by keefo** [comment]
目前这个服务匹配率在到 89%~91%左右。全本文章可能匹配率高一些。某一些类型的小说匹配率也高一些。有时候匹配不上，可能跟文件名也有关系。改个文件名就可以搜到了。所以这个服务我们肯定会不断改进，提高匹配率的。

**Comment by Csineneo** [comment]
找到问题了，查询的时候会把文本开头一段文字一起提交上去，我是在另一本书上搜索「全球高武」，所以没有返回结果，在对应书上就有返回结果了

**Comment by keefo** [comment]
这个问题我就先关闭了。
