### ISSUE TITLE
朗读图标显示错误

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#20]
如图所示
![image](https://user-images.githubusercontent.com/1370009/56105314-2d25bd00-5f6e-11e9-8ecb-cabfc0e36e3e.png)

**Comment by keefo** [comment]
1.8.3 里应该会修复。

**Comment by keefo** [comment]
1.8.3 已经发布了。

**Comment by Csineneo** [comment]
谢谢，没有再遇到了
