### ISSUE TITLE
超牛小说macOS Catalina出现空白无法显示文字

### ISSUE THREAD

**Issue by johnyang007** [Beyondcow/BeyondcowTxtReader#24]
超牛小说macOS Catalina Apple Store最新版本，在全屏或者最大化时，查看小说一段时间出现大面积空白页面，无法显示文字。调整窗口大小后可以恢复正常显示文字。请修复一下

**Comment by harrietable** [comment]
相同的情况，而且我是习惯在窗口看，快速滑过没有问题，但是正常阅读中会出现空白，点击后过段时间才会恢复

**Comment by keefo** [comment]
谢谢反馈。 
我们会尽快排查这个问题，稍后在这里更新进度。

**Comment by keefo** [comment]
目前我们在 10.15 (19A602) 下测试超牛 1.9.1 (232) 未能复现这个问题。
请问你们是在 10.15 (19A602) 下出现的问题吗？

**Comment by johnyang007** [comment]
是的，是在10.15下，有一定几率出现，需要持续翻看很长一段时间才会出现




| |
杨昆
18511898860
邮箱：yangkun0318@126.com
|

签名由 网易邮箱大师 定制

在2019年10月21日 02:55，Xu Lian 写道：

目前我们在 10.15 (19A602) 下测试超牛 1.9.1 (232) 未能复现这个问题。
请问你们是在 10.15 (19A602) 下出现的问题吗？

**Comment by harrietable** [comment]
我是在10.15 (19A583)下出现这个问题的

**Comment by keefo** [comment]
@johnyang007 给你发了一个测试版本到邮箱。

**Comment by keefo** [comment]
请试试 1.9.4 这个版本是否还有这个问题。多谢了。

**Comment by johnyang007** [comment]
1.9.4 更新后用了一段时间没出现空白没有文字的情况了。我再用一段时间看看，有问题再过来反馈

**Comment by johnyang007** [comment]
[屏幕录制2019-11-22下午10.53.21-2.mov.zip](https://github.com/Beyondcow/BeyondcowTxtReader/files/3880046/2019-11-22.10.53.21-2.mov.zip)

大约放了一天多，再打开电脑还是出现了空白。昨天应该是没有。

**Comment by keefo** [comment]
@johnyang007 谢谢跟进反馈。我们的开发人员已经复现这个问题。目前在尝试新的解决方案，希望能在 1.9.5 里修复。

**Comment by keefo** [comment]
1.9.5 已经提交审核。

**Comment by keefo** [comment]
1.9.5 已经上架。很快就应该可以更新了。

**Comment by keefo** [comment]
@johnyang007 @harrietable 经过我们的 4 天测试，1.9.5 没有在遇到这个问题了。我把该问题关闭了。如果你们又遇到了这个问题。请开一个新的 issue。谢谢了。
