### ISSUE TITLE
 根据日夜交替自动切换主题

### ISSUE THREAD

**Issue by keefo** [Beyondcow/BeyondcowTxtReader#25]
> 只是个人白天习惯使用系统的千岁绿主题 晚上喜欢使用自定义的黑色纹理背景，如果技术上可以实现的话下版本能否加入自定义时间段切换自选主题，或快捷键切换两种主题。（最好是可以随系统再日出日落切换自选的两种主题）

- 根据日夜交替自动切换主题
- 快捷键切换两种主题

**Comment by seaboyang** [comment]
非常感谢此建议能被采纳并且以高效率增加了此项功能。关于现版本个人还有两个小小遗憾在这里反馈下：昼夜模式不可以设置自定义主题，还有第三方应用 popcilp的选中快捷操作弹出支持（在阅读过程中偶尔遇到生僻字词或单词需要查询，习惯选中后直接在 popclip 设置好的选项中进行操作，但是阅读器内的好像只能通过右键复制的方式再到浏览器内查询，希望下版本可以改善这个问题）

**Comment by keefo** [comment]
1.9.4 已经增加次功能。
