### ISSUE TITLE
显示阅读进度百分比%或页数

### ISSUE THREAD

**Issue by happkitty** [Beyondcow/BeyondcowTxtReader#27]
请问阅读界面能否显示阅读进度百分比%或页数？谢谢！

**Comment by keefo** [comment]
确定你的版本号是  Version 1.9.6 (246)
然后鼠标移动到阅读窗口下部，就会出现进度了。

**Comment by keefo** [comment]
另外，因为目前的阅读窗口不是分页模式，所以不会有页数这个数据。分页模式也是我们正在开发的功能之一。
