### ISSUE TITLE
為什麼沒有了簡>繁的功能？

### ISSUE THREAD

**Issue by kiranc88** [Beyondcow/BeyondcowTxtReader#37]
為什麼沒有了簡>繁的功能？

**Comment by keefo** [comment]
谢谢报告。
已经记录到这里了。
https://github.com/Beyondcow/BeyondcowTxtReader/issues/36
下个版本会恢复这个功能。

**Comment by keefo** [comment]
1.9.13 已经发布，其中增加了动态中文编码转换。

◆ 改进 UI 设计细节。
◆ 增加动态中文繁简转换功能。
◆ 修复透明主题失效问题。
