### ISSUE TITLE
使用 moom 调整窗口宽度后文字不会重新排版

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#4]
我使用 [Moom](https://manytricks.com/moom/) 管理窗口，但通过 moom 调整窗口宽度后，文字不会重新排版，只有通过鼠标拖曳边框调整窗口宽度时才会重新排版文字。

另外，是否可以增加初始窗口大小的选项，每次打开 App 的窗口都太小了，总需要调整

**Comment by keefo** [comment]
消息反馈。会在 1.7.2 里修复。

**Comment by BeyondcowSupport** [comment]
新版本 1.7.2 已经提交审核。

**Comment by Csineneo** [comment]
谢谢，工作正常
