### ISSUE TITLE
meta数据可以自定义编辑么？

### ISSUE THREAD

**Issue by bzqlki** [Beyondcow/BeyondcowTxtReader#40]
有时候搜索取不到封面的时候，可以自己插一张封面进去么？——明明起点或者其他网站有这本书，就是app搜不到……

**Comment by keefo** [comment]
目前不支持手动编辑。我们服务器是支持动态增加记录的。有可能稍后系统就补充上你的这本书了。如果方便你也可以告诉我一下书名，我帮你查查。

**Comment by bzqlki** [comment]
我目前有这些书找不到meta信息


民国奇人   南无袈裟理科佛
最后一个修真者   纸上飞雪
奋斗在红楼    九悟
叛徒   端午正阳（中秋月明）

**Comment by keefo** [comment]
<img width="418" alt="Screen Shot 2020-06-14 at 5 36 10 PM" src="https://user-images.githubusercontent.com/809588/84608079-90a6c580-ae65-11ea-9969-9938c1a267de.png">
我试了一下，目前已经都有了。

**Comment by keefo** [comment]
你右键菜单里，重新搜索一下就应该可以出现了。

**Comment by bzqlki** [comment]
还是希望能开放metadata自定义，至少是能插一张封面进去，我发现我看的小说经常是没有封面的，不可能每次有一本出了问题，都来报告这样的「bug」吧？
现在有这些：
漫威里的德鲁伊
蜀汉的复兴
灵山
巫师不朽
……
还有好多

**Comment by keefo** [comment]
1.9.18 已经增加 meta 编辑功能。
