### ISSUE TITLE
数字显示出现重叠问题

### ISSUE THREAD

**Issue by keefo** [Beyondcow/BeyondcowTxtReader#46]
数字重叠 5
Edit Response
by ^_^爱华 – Edited Dec 17, 2020
文中出现阿拉伯数字的时候，经常数字会重叠，导致看不清楚，尝试各种字体均无效，烦请修正BUG

**Comment by lovingchina** [comment]
补充：主要出现在中文与少量数字混排的部分，例如「装甲掷弹兵第2师」这样。

**Comment by keefo** [comment]
@lovingchina 是否可以发个截图看看情况。我这边可以看到文字数字比较近，但是并未发生重叠情况。

**Comment by keefo** [comment]
![Screen Shot 2021-01-05 at 8 18 08 PM](https://user-images.githubusercontent.com/809588/103728549-33a26680-4f93-11eb-800b-af5367670635.jpg)

**Comment by lovingchina** [comment]
你好！

近期这段时间，发现使用「宋体」或「方正悠宋」之后，再无出现此类情况。

之前主要使用「苹方」和「兰亭黑」字体，但是现在短时间内我也无法复现BUG，不知道是不是近期App升级了版本的原因。

以上，如有再次观测到此问题，会截图反馈给你。谢谢！


lovingchina
✉ lovingchina@qq.com

**Comment by lovingchina** [comment]
刚看到一处接近BUG的情况，虽然还没有之前看到数字直接重叠那么严重，但是明显和正常排版不同，供参考。


lovingchina
✉ lovingchina@qq.com

**Comment by keefo** [comment]
@lovingchina  谢谢。
我们已经复现这个问题。

**Comment by keefo** [comment]
@lovingchina 我们会在 1.9.12 包含这个问题的修复。

**Comment by lovingchina** [comment]
(๑•̀ㅂ•́)و✧ 赞！


lovingchina
✉ lovingchina@qq.com
