### ISSUE TITLE
最新版本在mojave10.14.6系统下提示程序毁坏

### ISSUE THREAD

**Issue by 22haha** [Beyondcow/BeyondcowTxtReader#49]
更新最新版本后，在Mac pro mojave10.14.6系统下无法打开，提示程序毁坏，卸载重装还是一样。希望能修复

**Comment by fotomxq** [comment]
+1 一样的问题，希望尽快修复。

**Comment by keefo** [comment]
感谢报告。我们已经提交修复，等待审核中。

**Comment by keefo** [comment]
新版本 1.9.11 已经审核并上架。
