### ISSUE TITLE
支持 macOS 内置字典查词

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#5]
目前无法通过三指点击来查词，无法选中文本复制到其他 App 中查词

**Comment by keefo** [comment]
消息反馈。会在 1.7.2 里修复。

**Comment by BeyondcowSupport** [comment]
新版本 1.7.2 已经提交审核。

**Comment by Csineneo** [comment]
谢谢，右键搜索有了，但是三指点击查词还是不支持？

**Comment by keefo** [comment]
发现三指取词目前在 Mojave 和不同 Mac 电脑下有问题。有的设备就无法做 3 指取词。
稍后继续研究。

**Comment by keefo** [comment]
这个问题，已经找到解决方法。应该会在 1.8.2 里发布。

**Comment by Csineneo** [comment]
非常感谢
