### ISSUE TITLE
app更新至1.9.10后无法打开使用

### ISSUE THREAD

**Issue by 871117lucy** [Beyondcow/BeyondcowTxtReader#50]
![1609565516727](https://user-images.githubusercontent.com/76860718/103451443-1f463b80-4cff-11eb-9b9a-8d47bd8d1894.jpg

MacBookpro 版本为最新版本  macOS big sur 11.1 
于2021.1.2 更新后 无法使用 app 并且 删除重新下载安装后 还是无法打开

**Comment by 22haha** [comment]
Mac pro mojave10.14.6 都有這情況

**Comment by Csineneo** [comment]
+1，Big Sur 11.2

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1370009/103452143-18bbc200-4d07-11eb-8123-15e0ecfb1c1f.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1370009/103452147-1f4a3980-4d07-11eb-9f88-9fcc4483390f.png">

**Comment by keefo** [comment]
感谢报告。我们已经提交修复，等待审核中。

**Comment by nannanvicky** [comment]
如上，更新电脑后，app弹出“已损坏，无法打开”窗口，在删除后重新下载后依旧如此。希望快点解决此问题！

**Comment by keefo** [comment]
新版本 1.9.11 已经审核并上架。
