### ISSUE TITLE
朗读突然不能使用

### ISSUE THREAD

**Issue by nicoleyang415** [Beyondcow/BeyondcowTxtReader#52]
Big Sur 11.3, M1芯片，之前一直都能正常使用朗读的功能，今天打开之后提示声音不可用要自行下载语音，但是系统下好了语音依然不能用。这两天有更新过系统，不知道跟这个有没有关系
![截屏2021-04-30 下午1 22 20](https://user-images.githubusercontent.com/83469243/116731033-36e4b680-a9b7-11eb-8d3c-59b47f376853.png)
![截屏2021-04-30 下午1 21 50](https://user-images.githubusercontent.com/83469243/116731073-3f3cf180-a9b7-11eb-813b-6879430df5fb.png)

**Comment by keefo** [comment]
已经在测试中。很快发布新版本。

**Comment by keefo** [comment]
新版本已经修复该问题。
