### ISSUE TITLE
自選字體功能失效

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#55]
版本： 1.9.15
系統版本： MacOS 11.5

**Comment by Csineneo** [comment]
1.9.13 正常

**Comment by keefo** [comment]
Version 1.9.17(262) 已经修复了这个功能。

**Comment by Csineneo** [comment]
自選字體依舊有問題，只有預設字體列表中的字體有效，但不能選擇字重

1.9.18(264), MacOS 11.6.2

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1370009/146300070-40e78eca-3a23-4336-9744-138530fcfb29.png">

**Comment by youwillbe** [comment]
自选字体不起作用了，之前版本还没问题的，版本`1.9.18(264)`，系统版本`macOS Sonoma 14.5`
