### ISSUE TITLE
打开txt经常白屏

### ISSUE THREAD

**Issue by DipsySu** [Beyondcow/BeyondcowTxtReader#56]
![image](https://user-images.githubusercontent.com/13214404/132818164-732f68de-8c4f-4dee-bf97-eda6fea111c9.png)
version : Version 1.9.16(261)
osVersion:  11.5.2 (20G95)

**Comment by keefo** [comment]
HI @oooldCaption 感谢反馈。新版本已经提交。稍后就可以更新了。

**Comment by keefo** [comment]
1.9.17 已经通过审核，目前在分发阶段。
