### ISSUE TITLE
没有元信息功能

### ISSUE THREAD

**Issue by begonia25** [Beyondcow/BeyondcowTxtReader#57]
为什么不能编辑元信息？
帮助里面显示有这个功能的呀
<img width="322" alt="Screenshot 2021-10-22 at 18 12 09" src="https://user-images.githubusercontent.com/92982673/138436859-d7cfafe6-c35a-4aaf-8a61-eea88e9e4465.png">

不能编辑太混乱了，这个app买来没用，几百个txt都不能根据作者分类，也不能添加封面

**Comment by keefo** [comment]
1.9.18 已经增加编辑功能。
