### ISSUE TITLE
高亮不明显

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#6]
搜索和选取的文本高亮不明显，没有继承系统的设定
![image](https://user-images.githubusercontent.com/1370009/47283403-e33ec880-d615-11e8-8baf-54cd62a87e2b.png)

**Comment by keefo** [comment]
谢谢反馈。之所以没有继承系统设定是因为，继承系统高亮颜色，那么有可能会出现阅读背景色和高亮色接近的情况。所以用了一个计算反色。
下个版本会考虑优化一下这里。

**Comment by keefo** [comment]
1.7.3 版本已经发布。
