### ISSUE TITLE
[Feature Request] 自动移除空行

### ISSUE THREAD

**Issue by Csineneo** [Beyondcow/BeyondcowTxtReader#7]
有些時候遇到一些文本中有大量空行，影响阅读，希望可以自动移除

空行不只是换行，还包含中英文空格

**Comment by keefo** [comment]
目前版本多空行是已经过滤掉的。情况我的截图。
![screen shot 2018-11-22 at 10 30 28 pm](https://user-images.githubusercontent.com/809588/48930563-3bcbe480-eea6-11e8-989f-6633d90090ce.png)

你如果遇到例子可以出现大量空行请发给我，我测试一下。

**Comment by Csineneo** [comment]
![image](https://user-images.githubusercontent.com/1370009/48964493-74bda380-efe3-11e8-91b2-42684f254779.png)
[test.txt](https://github.com/Beyondcow/BeyondcowTxtReader/files/2612005/test.txt)

**Comment by keefo** [comment]
谢谢提供的数据。
已经修复，稍后发布。

**Comment by keefo** [comment]
1.7.3 版本已经发布。
